server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/flight_db"
    username: "postgres"
    password: "password"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: "classpath:db/migration"

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "${MAIL_USERNAME:qafarali91@gmail.com}"
    password: "${MAIL_PASSWORD:iyjpjrdpmckoztss}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "${APP_JWT_SECRET:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}"  # Base64 256-bit
    expiration-ms: 86400000
